### ISSUE TITLE
您好，请问怎么使用composer安装和使用？

### ISSUE THREAD

**Issue by BEIBEI123** [ChiHoc/WechatShop#1]
您好，我看了下您的项目，非常好，全github上就您的项目对微信小店的支持和分装最全面，如果能使用composer安装那最好了吗，感谢您的贡献

**Comment by ChiHoc** [comment]
您好，我会尽快支持composer安装的。

**Comment by ChiHoc** [comment]
已支持composer安装，详情看README。

**Comment by BEIBEI123** [comment]
非常感谢
